encrypt:
  key: 'superSERCRET'
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/zHazyl/myc-config-resource'
          search-paths:
            - 'files'
            - 'files/service/commons'
            - 'files/service/*-service'
          default-label: 'main'
server:
  port: 8071